# Change these first
owner: Feiert-ag # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
user-agent: MopsFrank

sites:
  - name: 'Feiert.ag'
    url: https://Feiert.ag
    __dangerous__body_down_if_text_missing: 'Feiertag Eventkommunikation ist ein Angebot von <a href="https://www.Doebeling.de"'
    icon: https://avatars.githubusercontent.com/u/156091420
    maxResponseTime: 500
    skipDeleteIssues: true
    assignees:
    - ADoebeling

  - name: 'www.Feiert.ag (Redirect)'
    url: https://www.Feiert.ag
    icon: https://avatars.githubusercontent.com/u/156091420
    maxResponseTime: 500
    skipDeleteIssues: true
    expectedStatusCode:
    - 301
    assignees:
    - ADoebeling
    
  - name: 'CalDB.de'
    url: https://CalDB.de
    __dangerous__body_down_if_text_missing: '"/v1/projects":{"get":{"operationId":"api_v1projects_get_collection","tags":["Project"],"responses":{"200":{"description":"Project collection"'
    icon: https://www.openapis.org/wp-content/uploads/sites/3/2019/06/favicon-140x140.png
    maxResponseTime: 500
    skipDeleteIssues: true
    assignees:
    - ADoebeling

  - name: 'CalDB.de/v1/projects'
    url: https://CalDB.de/v1/projects
    headers:
    - "Authorization: Bearer $CALDB_TOKEN"
    - "Content-Type: application/json"
    - "User-Agent: Upptime/GitHub Action"
    __dangerous__body_down_if_text_missing: '"@id": "https://caldb.de/v1/projects/cafa1bf6-42a3-502f-ad67-9f0455946b56"'
    icon: https://www.openapis.org/wp-content/uploads/sites/3/2019/06/favicon-140x140.png
    maxResponseTime: 500
    skipDeleteIssues: true
    assignees:
    - ADoebeling

  - name: 'github.com/Feiert.ag'
    url: https://github.com/feiert-ag/
    __dangerous__body_down_if_text_missing: 'Feiert.ag Eventkommunikation'
    icon: https://github.com/favicon.ico
    maxResponseTime: 1000
    skipDeleteIssues: true

  - name: 'Referenz: Google.com'
    url: https://google.com
    icon: https://www.google.com/favicon.ico
    maxResponseTime: 1000
    skipDeleteIssues: true

  - name: 'Referenz: Cloudflare.com'
    url: https://cloudflare.com
    icon: https://cloudflare.com/favicon.ico
    maxResponseTime: 1000
    skipDeleteIssues: true

  - name: 'Referenz: Amazon.com'
    url: https://amazon.com
    icon: https://amazon.com/favicon.ico
    maxResponseTime: 1000
    skipDeleteIssues: true



status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.feiert.ag
  robotsText: "User-agent: * \n Disallow: /"
  theme: light
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/156091420
  name: Status
  introTitle: "Status der Systeme von Feiert.ag / CalDB.de"
  navbar:
    - title: Status
      href: /
    - title: Feiert.ag
      href: https://Feiert.ag
    - title: CalDB.de
      href: https://CalDB.de
    - title: Issues on GitHub
      href: https://github.com/Feiert-ag/status/issues
      


commitMessages:
  commitAuthorName: "MopsFrank [bot]"
  commitAuthorEmail: "mopsfrank.bot@doebeling.de"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
