# Change these first
owner: Feiert-ag # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
user-agent: MopsFrank

sites:
  # Until our own monitoring exists, only the landing page is checked (DOEBELING/Feiert.ag#496)
  - name: 'Feiert.ag'
    url: https://Feiert.ag
    __dangerous__body_down_if_text_missing: 'Hier startet Deine Feier'
    icon: https://avatars.githubusercontent.com/u/156091420
    maxResponseTime: 1000
    skipDeleteIssues: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.feiert.ag
  robotsText: "User-agent: * \n Disallow: /"
  theme: light
  links:
    - rel: stylesheet
      href: /width-bugfix.css
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/156091420
  name: Status
  introTitle: "Status of Feiert.ag"
  navbar:
    - title: Status
      href: /
    - title: Feiert.ag
      href: https://Feiert.ag
    - title: Issues on GitHub
      href: https://github.com/Feiert-ag/status/issues

i18n:
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)<br>[Impressum](https://legal.doebeling.de/impressum), [Datenschutzerklärung](https://legal.doebeling.de/datenschutzerklaerung)


commitMessages:
  commitAuthorName: "MopsFrank [bot]"
  commitAuthorEmail: "mopsfrank.bot@doebeling.de"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
