# Change these first
owner: Feiert-ag # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
user-agent: MopsFrank

sites:
  - name: 'Feiert.ag'
    url: https://Feiert.ag
    __dangerous__body_down_if_text_missing: 'Feiertag Eventkommunikation ist ein Angebot von <a href="https://www.Doebeling.de"'
    icon: https://avatars.githubusercontent.com/u/156091420
    maxResponseTime: 500
    skipDeleteIssues: true

  - name: 'www.Feiert.ag (Redirect)'
    url: https://www.Feiert.ag
    icon: https://avatars.githubusercontent.com/u/156091420
    maxResponseTime: 500
    skipDeleteIssues: true
    expectedStatusCode:
    - 301

  - name: 'Feiert.ag:80 (Redirect)'
    url: http://Feiert.ag
    icon: https://avatars.githubusercontent.com/u/156091420
    maxResponseTime: 500
    skipDeleteIssues: true
    expectedStatusCode:
      - 301
    
  - name: 'CalDB.de (Public)'
    url: https://CalDB.de
    __dangerous__body_down_if_text_missing: 'Example'
    icon: https://avatars.githubusercontent.com/u/16343502
    maxResponseTime: 500
    skipDeleteIssues: true

  - name: 'CalDB.de (Webserver)'
    url: https://$CALDB_WEBSERVER
    __dangerous__body_down_if_text_missing: 'Example'
    __dangerous__disable_verify_peer: true
    icon: https://konsoleh.hetzner.com/favicon.ico
    maxResponseTime: 500
    skipDeleteIssues: true

  - name: 'CalDB.de (SSH)'
    url: $CALDB_WEBSERVER
    port: 22
    icon: https://avatars.githubusercontent.com/u/2387206
    maxResponseTime: 500
    skipDeleteIssues: true

  - name: 'www.CalDB.de (Redirect)'
    url: https://www.CalDB.de
    icon: https://avatars.githubusercontent.com/u/16343502
    maxResponseTime: 500
    skipDeleteIssues: true
    expectedStatusCode:
      - 301

  - name: 'CalDB.de:80 (Redirect)'
    url: 'http://www.CalDB.de'
    icon: https://avatars.githubusercontent.com/u/16343502
    maxResponseTime: 500
    skipDeleteIssues: true
    expectedStatusCode:
      - 301

  - name: 'Projects-Service: Read'
    url: https://CalDB.de/v1/projects/12345678-0000-0000-0000-000000000001
    headers:
    - "Authorization: Bearer $CALDB_TOKEN"
    - "Content-Type: application/json"
    - "User-Agent: Upptime/GitHub Action"
    __dangerous__body_down_if_text_missing: 'Example'
    icon: https://avatars.githubusercontent.com/u/16343502
    maxResponseTime: 500
    skipDeleteIssues: true

  - name: 'Domains-Service: Read'
    url: https://CalDB.de/v1/domains/12345678-0000-0000-0000-000000000001
    headers:
      - "Authorization: Bearer $CALDB_TOKEN"
      - "Content-Type: application/json"
      - "User-Agent: Upptime/GitHub Action"
    __dangerous__body_down_if_text_missing: 'Example'
    icon: https://avatars.githubusercontent.com/u/16343502
    maxResponseTime: 500
    skipDeleteIssues: true

  - name: 'Themes-Service: Read'
    url: https://CalDB.de/v1/themes/12345678-0000-0000-0000-000000000001
    headers:
      - "Authorization: Bearer $CALDB_TOKEN"
      - "Content-Type: application/json"
      - "User-Agent: Upptime/GitHub Action"
    __dangerous__body_down_if_text_missing: 'Example'
    icon: https://avatars.githubusercontent.com/u/16343502
    maxResponseTime: 500
    skipDeleteIssues: true

  - name: 'Templates-Service: Read'
    url: https://CalDB.de/v1/themes/12345678-0000-0000-0000-000000000001
    headers:
      - "Authorization: Bearer $CALDB_TOKEN"
      - "Content-Type: application/json"
      - "User-Agent: Upptime/GitHub Action"
    __dangerous__body_down_if_text_missing: 'Example'
    icon: https://avatars.githubusercontent.com/u/16343502
    maxResponseTime: 500
    skipDeleteIssues: true

  - name: 'Views-Service: Read'
    url: https://CalDB.de/v1/themes/12345678-0000-0000-0000-000000000001
    headers:
      - "Authorization: Bearer $CALDB_TOKEN"
      - "Content-Type: application/json"
      - "User-Agent: Upptime/GitHub Action"
    __dangerous__body_down_if_text_missing: 'Example'
    icon: https://avatars.githubusercontent.com/u/16343502
    maxResponseTime: 500
    skipDeleteIssues: true

  - name: 'Views-Service: Write'
    url: https://CalDB.de/v1/themes
    method: POST
    headers:
      - "Authorization: Bearer $CALDB_TOKEN"
      - "Content-Type: application/json"
      - "User-Agent: Upptime/GitHub Action"
    body: tbd
    expectedStatusCode:
        - 201
    icon: https://avatars.githubusercontent.com/u/16343502
    maxResponseTime: 500
    skipDeleteIssues: true

  - name: 'Calendars-Service: Read'
    url: https://CalDB.de/v1/calendars/12345678-0000-0000-0000-000000000001
    headers:
      - "Authorization: Bearer $CALDB_TOKEN"
      - "Content-Type: application/json"
      - "User-Agent: Upptime/GitHub Action"
    __dangerous__body_down_if_text_missing: 'Example'
    icon: https://avatars.githubusercontent.com/u/16343502
    maxResponseTime: 500
    skipDeleteIssues: true

  - name: 'Calendars-Service: Write'
    url: https://CalDB.de/v1/themes
    method: POST
    headers:
      - "Authorization: Bearer $CALDB_TOKEN"
      - "Content-Type: application/json"
      - "User-Agent: Upptime/GitHub Action"
    body: tbd
    expectedStatusCode:
      - 201
    icon: https://avatars.githubusercontent.com/u/16343502
    maxResponseTime: 500
    skipDeleteIssues: true

  - name: 'Events-Service: Read'
    url: https://CalDB.de/v1/calendars/12345678-0000-0000-0000-000000000001
    headers:
      - "Authorization: Bearer $CALDB_TOKEN"
      - "Content-Type: application/json"
      - "User-Agent: Upptime/GitHub Action"
    __dangerous__body_down_if_text_missing: 'Example'
    icon: https://avatars.githubusercontent.com/u/16343502
    maxResponseTime: 500
    skipDeleteIssues: true

  - name: 'Events-Service: Write'
    url: https://CalDB.de/v1/themes
    method: POST
    headers:
      - "Authorization: Bearer $CALDB_TOKEN"
      - "Content-Type: application/json"
      - "User-Agent: Upptime/GitHub Action"
    body: tbd
    expectedStatusCode:
      - 201
    icon: https://avatars.githubusercontent.com/u/16343502
    maxResponseTime: 500
    skipDeleteIssues: true

  - name: 'Users-Service: Read'
    url: https://CalDB.de/v1/users/12345678-0000-0000-0000-000000000001
    headers:
      - "Authorization: Bearer $CALDB_TOKEN"
      - "Content-Type: application/json"
      - "User-Agent: Upptime/GitHub Action"
    __dangerous__body_down_if_text_missing: 'Example'
    icon: https://avatars.githubusercontent.com/u/16343502
    maxResponseTime: 500
    skipDeleteIssues: true

  - name: 'github.com/Feiert.ag'
    url: https://github.com/feiert-ag/
    __dangerous__body_down_if_text_missing: 'Feiert.ag Eventkommunikation'
    icon: https://github.com/favicon.ico
    maxResponseTime: 1000
    skipDeleteIssues: true

  - name: 'Reference: Google.com'
    url: https://google.com
    icon: https://www.google.com/favicon.ico
    maxResponseTime: 1000
    skipDeleteIssues: true

  - name: 'Reference: Cloudflare.com'
    url: https://cloudflare.com
    icon: https://cloudflare.com/favicon.ico
    maxResponseTime: 1000
    skipDeleteIssues: true

  - name: 'Reference: Amazon.com'
    url: https://amazon.com
    icon: https://amazon.com/favicon.ico
    maxResponseTime: 1000
    skipDeleteIssues: true



status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.feiert.ag
  robotsText: "User-agent: * \n Disallow: /"
  theme: light
  links:
    - rel: stylesheet
      href: /width-bugfix.css
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/156091420
  name: Status
  introTitle: "Status of Feiert.ag and CalDB.de"
  navbar:
    - title: Status
      href: /
    - title: Feiert.ag
      href: https://Feiert.ag
    - title: CalDB.de
      href: https://CalDB.de
    - title: Issues on GitHub
      href: https://github.com/Feiert-ag/status/issues

i18n:
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)<br>[Impressum](https://legal.doebeling.de/impressum), [Datenschutzerklärung](https://legal.doebeling.de/datenschutzerklaerung)


commitMessages:
  commitAuthorName: "MopsFrank [bot]"
  commitAuthorEmail: "mopsfrank.bot@doebeling.de"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
